Repository edu2andrade/booking-manager-system, pull requests merged in 2023-06, with the labels that each got.

#49 Front end update and delete booking by
  README.md
  migrations/versions/188b50086b2d_.py
  src/api/domain/booking/repository.py
  src/api/domain/booking/route.py
  src/api/models/booking.py
  src/assets/assets.jsx
  src/assets/avatar.png
  src/assets/bgImg.jpeg
  src/assets/bg_detail.png
  src/assets/calendar_box.png
  src/assets/imgDefault.png
  src/assets/logo_detail.png
  src/assets/logotipo-detail.png
  src/assets/models.png
  src/assets/navbar1.png
  src/assets/navbar2.png
  src/front/js/components/avatar/index.jsx
  src/front/js/components/bookingCard/index.jsx
  src/front/js/components/header/index.jsx
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/logotipo/index.jsx
  src/front/js/components/modalBooking/index.jsx
  src/front/js/components/modalBooking/modalBooking.module.css
  src/front/js/components/navbar/index.jsx
  src/front/js/components/serviceDetailCard/index.jsx
  src/front/js/components/serviceDetailCard/serviceDetailCard.module.css
  src/front/js/components/updateBookingCard/index.jsx
  src/front/js/components/updateBookingCard/updateBookingCard.module.css
  src/front/js/components/updateMessage/index.jsx
  src/front/js/components/updateMessage/updateMessage.module.css
  src/front/js/components/updateServiceCard/index.jsx
  src/front/js/components/updateServiceCard/updateServiceCard.module.css
  src/front/js/layout.js
  src/front/js/pages/RecoveryPassword/index.jsx
  src/front/js/pages/companyRegister/index.jsx
  src/front/js/pages/companyRegisterStep2/index.jsx
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/createWorker/index.jsx
  src/front/js/pages/home/index.jsx
  src/front/js/pages/login/index.jsx
  src/front/js/pages/serviceDetail/index.jsx
  src/front/js/pages/serviceList/index.jsx
  src/front/js/pages/updateBooking/index.jsx
  src/front/js/pages/updatePassword/index.jsx
  src/front/js/pages/updateService/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/pages/userRegister/index.jsx
  src/front/js/service/booking.js
Labels: enhancement

#61 Update profile
  migrations/versions/48a73d50e19f_.py
  migrations/versions/65e74337b55d_.py
  migrations/versions/cd046555e142_.py
  src/front/js/components/imgProfile/imgProfile.module.css
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/input/index.jsx
  src/front/js/components/profileForm/index.jsx
  src/front/js/components/profileForm/profileForm.module.css
  src/front/js/components/profileForm/styles.css
  src/front/js/components/updateServiceCard/updateServiceCard.module.css
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/profile/profile.module.css
  src/front/js/pages/profile/styles.css
  src/front/js/store/flux.js
Labels: enhancement

#62 Backend services responses
  src/api/domain/booking/controller.py
  src/api/domain/booking/route.py
  src/api/domain/company/controller.py
  src/api/domain/company/route.py
  src/api/domain/service_worker/controller.py
  src/api/domain/service_worker/route.py
  src/api/domain/services/controller.py
  src/api/domain/services/route.py
  src/api/domain/users/controller.py
  src/api/domain/users/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/route.py
  src/front/js/components/imgProfile/index.jsx
  src/front/js/pages/profile/index.jsx
Labels: enhancement

#65 Front/spinners/toasts
  src/api/domain/company/controller.py
  src/api/domain/service_worker/route.py
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/profileForm/index.jsx
  src/front/js/pages/adminCreateBooking/index.jsx
  src/front/js/pages/companyRegister/index.jsx
  src/front/js/pages/companyRegisterStep2/index.jsx
  src/front/js/pages/createNewBooking/index.jsx
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/createWorker/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/servicesWorkers/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/pages/userRegister/index.jsx
  src/front/js/service/booking.js
  src/front/js/service/company.js
  src/front/js/service/user.js
Labels: enhancement

#66 Fix/frontend header
  src/front/js/components/header/header.module.css
  src/front/js/components/header/index.jsx
  src/front/js/pages/adminDashboard/adminDashboard.module.css
  src/front/js/pages/adminDashboard/index.jsx
  src/front/js/pages/home/index.jsx
  src/front/styles/index.css
Labels: bug

#64 Fix details update profile
  package-lock.json
  package.json
  src/api/domain/users/controller.py
  src/api/domain/users/route.py
  src/front/js/components/imgProfile/imgProfile.module.css
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/inputField/index.jsx
  src/front/js/components/inputField/inputField.module.css
  src/front/js/components/profileForm/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/profile/profile.module.css
  src/front/js/store/flux.js
Labels: duplicate

#63 Validation login
  migrations/versions/9930170efc3a_.py
  src/front/js/components/inputField/index.jsx
  src/front/js/components/inputField/inputField.module.css
  src/front/js/components/loginForm/index.jsx
  src/front/js/components/loginForm/login.module.css
  src/front/js/pages/login/index.jsx
  src/front/js/pages/login/login.module.css
Labels: enhancement

#68 Front/company/registration
  package-lock.json
  src/api/domain/company/controller.py
  src/front/js/components/companyForm/companyForm.module.css
  src/front/js/components/companyForm/index.jsx
  src/front/js/components/header/index.jsx
  src/front/js/components/input/index.jsx
  src/front/js/components/input/input.module.css
  src/front/js/components/userForm/index.jsx
  src/front/js/components/userForm/userForm.module.css
  src/front/js/pages/adminCreateBooking/index.jsx
  src/front/js/pages/companyRegister/index.jsx
  src/front/js/pages/companyRegisterStep2/index.jsx
  src/front/js/service/company.js
  src/front/js/service/user.js
  src/front/js/validations/companyValidation.js
  src/front/js/validations/userFormValidation.js
Labels: enhancement

#69 Company worker details
  src/front/js/components/btnService/btnService.module.css
  src/front/js/components/btnService/index.jsx
  src/front/js/components/loginForm/index.jsx
  src/front/js/components/modalCompany/index.jsx
  src/front/js/components/modalCompany/modalCompany.module.css
  src/front/js/pages/companyDetails/company-details.module.css
  src/front/js/pages/companyDetails/index.jsx
Labels: enhancement

#72 Front/creat service
  src/front/js/components/serviceForm/index.jsx
  src/front/js/components/serviceForm/serviceForm.module.css
  src/front/js/components/userForm/index.jsx
  src/front/js/components/workerForm/index.jsx
  src/front/js/pages/createService/index.jsx
  src/front/js/validations/serviceValidation.js
Labels: enhancement

#73 Front/create/company/button
  src/front/js/components/userCompanyForm/index.jsx
  src/front/js/components/workerForm/index.jsx
  src/front/js/pages/companyRegisterStep2/index.jsx
Labels: enhancement

#74 Front/password/fix/input
  src/front/js/components/companyForm/index.jsx
  src/front/js/components/userCompanyForm/index.jsx
  src/front/js/components/userForm/index.jsx
Labels: enhancement

#75 Front/back/createworker/delete working schedule
  src/api/domain/workers/repository.py
  src/front/js/components/inputField/index.jsx
  src/front/js/components/inputField/inputField.module.css
  src/front/js/components/loginForm/index.jsx
  src/front/js/components/workerForm/index.jsx
Labels: enhancement

#76 fix: edit function services list
  src/front/js/components/companyForm/index.jsx
  src/front/js/components/serviceForm/index.jsx
  src/front/js/components/updateServiceCard/index.jsx
  src/front/js/components/updateServiceCard/updateServiceCard.module.css
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/createWorker/index.jsx
  src/front/js/pages/serviceList/index.jsx
  src/front/js/pages/serviceList/serviceList.module.css
  src/front/js/pages/updateService/index.jsx
Labels: bug

#77 Front-ASSIGN-SERVICE
  src/front/js/components/inputField/index.jsx
  src/front/js/components/loginForm/index.jsx
  src/front/js/pages/companyDetails/company-details.module.css
  src/front/js/pages/companyDetails/index.jsx
  src/front/js/pages/servicesWorkers/index.jsx
  src/front/js/pages/servicesWorkers/servicesWorkers.module.css
Labels: enhancement

#78 Updateprofile back front
  package-lock.json
  package.json
  src/front/js/components/inputField/inputField.module.css
  src/front/js/components/userCompanyForm/index.jsx
  src/front/js/components/userForm/index.jsx
  src/front/js/components/workerForm/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/servicesWorkers/index.jsx
  src/front/js/pages/servicesWorkers/servicesWorkers.module.css
Labels: enhancement

#79 Front/admin/booking
  package-lock.json
  package.json
  src/api/domain/booking/route.py
  src/api/models/booking.py
  src/api/models/services_workers.py
  src/front/js/components/adminReservationForm/adminReservationForm.module.css
  src/front/js/components/adminReservationForm/index.jsx
  src/front/js/components/companyForm/index.jsx
  src/front/js/components/datePicker/datePicker.module.css
  src/front/js/components/datePicker/index.jsx
  src/front/js/pages/adminCreateBooking/adminCreateBooking.module.css
  src/front/js/pages/adminCreateBooking/index.jsx
  src/front/js/pages/createNewBooking/createNewBooking.module.css
  src/front/js/pages/createNewBooking/index.jsx
  src/front/js/pages/workerDashboard/index.jsx
  src/front/js/service/booking.js
Labels: enhancement

#80 Front/user/booking
  package-lock.json
  src/front/js/components/adminCalendar/adminCalendar.module.css
  src/front/js/components/adminReservationForm/adminReservationForm.module.css
  src/front/js/components/reservationForm/index.jsx
  src/front/js/components/reservationForm/reservationForm.module.css
  src/front/js/pages/companyDetails/company-details.module.css
  src/front/js/pages/companyDetails/index.jsx
  src/front/js/pages/createNewBooking/index.jsx
Labels: enhancement
