Repository edu2andrade/booking-manager-system, pull requests merged in 2023-05, with the labels that each got.

#14 feat: endpoint-worker
  .vscode/settings.json
  migrations/versions/4adc01c41a67_.py
  migrations/versions/dddc3e5c4b03_.py
  migrations/versions/fd46aef4a380_.py
  src/api/domain/company/repository.py
  src/api/domain/company/route.py
  src/api/domain/users/controller.py
  src/api/domain/users/repository.py
  src/api/domain/users/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/repository.py
  src/api/domain/workers/route.py
  src/api/models/workers.py
  src/app.py
Labels: enhancement

#15 fix: endpoint-worker
  src/api/domain/workers/controller.py
  src/api/domain/workers/repository.py
  src/api/domain/workers/route.py
  src/api/models/workers.py
Labels: duplicate

#16 Feature/service endpoints
  migrations/versions/217020d29b64_.py
  src/api/domain/services/controller.py
  src/api/domain/services/repository.py
  src/api/domain/services/route.py
  src/api/models/company.py
  src/api/models/services.py
  src/api/models/user.py
Labels: enhancement

#17 Endpoint worker
  migrations/versions/a4e210bbf101_.py
  src/api/domain/company/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/repository.py
  src/api/domain/workers/route.py
Labels: duplicate

#13 feat: login page created
  migrations/versions/19e517af7228_.py
  migrations/versions/bea187ebfcbd_.py
  migrations/versions/f146d1ca8235_.py
  src/api/domain/users/repository.py
  src/api/domain/users/route.py
  src/front/js/pages/home/home.jsx
  src/front/js/pages/login/login.jsx
  src/front/js/pages/register/register.jsx
Labels: enhancement

#21 Api/domain/users
  src/api/domain/company/controller.py
  src/api/domain/company/repository.py
  src/api/domain/company/route.py
  src/api/domain/users/controller.py
  src/api/domain/users/repository.py
  src/api/domain/users/route.py
  src/api/models/company.py
  src/front/js/service/user.js
Labels: enhancement

#20 Endpoint service workers
  migrations/versions/66f811c1aadc_.py
  migrations/versions/a4e210bbf101_.py
  src/api/domain/company/controller.py
  src/api/domain/company/repository.py
  src/api/domain/company/route.py
  src/api/domain/service_worker/controller.py
  src/api/domain/service_worker/repository.py
  src/api/domain/service_worker/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/repository.py
  src/app.py
Labels: enhancement

#24 Workers/endpoints/model
  migrations/versions/19e517af7228_.py
  migrations/versions/66f811c1aadc_.py
  migrations/versions/a4a85fab55f0_.py
  migrations/versions/bea187ebfcbd_.py
  package-lock.json
  package.json
  src/api/domain/company/controller.py
  src/api/domain/company/repository.py
  src/api/domain/company/route.py
  src/api/domain/services/route.py
  src/api/domain/users/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/repository.py
  src/api/domain/workers/route.py
  src/api/models/workers.py
  src/front/js/components/calendar/calendar.jsx
  src/front/js/components/calendar/styles.css
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/pages/userDashboard/styles.css
  src/front/js/service/index.js
  src/front/js/service/user.js
Labels: enhancement

#26 Service workers routes
  src/api/domain/company/controller.py
  src/api/domain/company/repository.py
  src/api/domain/company/route.py
  src/api/domain/service_worker/controller.py
  src/api/domain/service_worker/repository.py
  src/api/domain/service_worker/route.py
  src/api/domain/services/route.py
  src/api/domain/workers/controller.py
  src/front/js/components/calendar/calendar.jsx
  src/front/js/components/calendar/styles.css
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/pages/userDashboard/styles.css
Labels: bug

#27 Front end profile
  .env.example
  migrations/versions/0693246901fd_.py
  migrations/versions/fef1174a6d3a_.py
  src/api/domain/users/controller.py
  src/api/domain/users/route.py
  src/api/models/user.py
  src/app.py
  src/assets/navbar1.png
  src/assets/navbar2.png
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/imgProfile/styles.css
  src/front/js/components/navbar/index.jsx
  src/front/js/components/navbar/styles.css
  src/front/js/components/profileForm/index.jsx
  src/front/js/components/profileForm/styles.css
  src/front/js/layout.js
  src/front/js/pages/RecoveryPassword/index.jsx
  src/front/js/pages/RecoveryPassword/styles.css
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/profile/styles.css
  src/front/js/pages/updatePassword/index.jsx
  src/front/js/pages/updatePassword/styles.css
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/service/index.js
  src/front/js/service/user.js
  src/front/js/store/flux.js
Labels: enhancement

#28 Feature/backend booking endpoints
  .env.example
  migrations/versions/4517192f6926_.py
  src/api/admin.py
  src/api/domain/booking/controller.py
  src/api/domain/booking/repository.py
  src/api/domain/booking/route.py
  src/api/domain/company/controller.py
  src/api/domain/service_worker/route.py
  src/api/domain/services/repository.py
  src/api/domain/users/controller.py
  src/api/domain/users/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/route.py
  src/api/models/booking.py
  src/api/models/services.py
  src/api/models/services_workers.py
  src/api/models/user.py
  src/app.py
Labels: enhancement

#30 feat: list companies page implemented
  .env.example
  migrations/versions/0693246901fd_.py
  migrations/versions/096a638c8c3d_.py
  migrations/versions/fef1174a6d3a_.py
  src/api/models/user.py
  src/assets/logotipo-detail.png
  src/front/js/components/bigContainer/index.jsx
  src/front/js/components/bigContainer/styles.css
  src/front/js/components/button/index.jsx
  src/front/js/components/button/styles.css
  src/front/js/components/itemContainer/index.jsx
  src/front/js/components/itemContainer/styles.css
  src/front/js/components/logotipo/index.jsx
  src/front/js/components/logotipo/styles.css
  src/front/js/layout.js
  src/front/js/pages/companiesList/index.jsx
  src/front/js/pages/companiesList/styles.css
  src/front/js/pages/companyRegisterStep2/index.jsx
  src/front/js/pages/home/index.jsx
  src/front/js/pages/home/styles.css
  src/front/js/pages/login/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/pages/userRegister/index.jsx
  src/front/js/service/company.js
  src/front/js/service/index.js
  src/front/styles/index.css
Labels: enhancement

#29 Front end create service
  migrations/versions/4f0c756c76d4_.py
  src/api/domain/company/route.py
  src/app.py
  src/assets/imgDefault.png
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/input/index.jsx
  src/front/js/components/profileForm/index.jsx
  src/front/js/layout.js
  src/front/js/pages/adminDashboard/index.jsx
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/createService/styles.css
  src/front/js/pages/login/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/service/company.js
  src/front/js/service/index.js
  src/front/js/service/service.js
  src/front/js/service/user.js
  template.html
Labels: enhancement

#31 Bookings list
  migrations/versions/9a812e3c6763_.py
  package-lock.json
  package.json
  src/api/domain/booking/controller.py
  src/api/domain/booking/repository.py
  src/api/domain/booking/route.py
  src/api/domain/workers/route.py
  src/front/js/components/bookingCard/index.jsx
  src/front/js/components/bookingCard/styles.css
  src/front/js/components/calendar/index.jsx
  src/front/js/components/calendar/styles.css
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/navbar/index.jsx
  src/front/js/components/time/index.jsx
  src/front/js/components/times/index.jsx
  src/front/js/components/times/styles.css
  src/front/js/pages/login/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/pages/userDashboard/styles.css
  src/front/js/service/booking.js
  src/front/js/service/index.js
  src/front/js/service/user.js
  src/front/styles/index.css
Labels: enhancement

#32 Front end list services
  src/front/js/layout.js
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/serviceList/index.jsx
  src/front/js/pages/serviceList/styles.css
  src/front/js/service/company.js
  src/front/js/service/index.js
  src/front/js/service/service.js
Labels: enhancement

#34 Front/create service worker
  migrations/versions/ce40dcf53f84_.py
  package-lock.json
  package.json
  src/api/domain/company/controller.py
  src/api/domain/company/repository.py
  src/api/domain/company/route.py
  src/api/models/user.py
  src/front/js/components/dropdown/index.jsx
  src/front/js/components/dropdown/styles.css
  src/front/js/components/toast/index.jsx
  src/front/js/components/toast/styles.css
  src/front/js/layout.js
  src/front/js/pages/adminDashboard/index.jsx
  src/front/js/pages/servicesWorkers/index.jsx
  src/front/js/pages/servicesWorkers/styles.css
  src/front/js/service/company.js
  src/front/js/service/index.js
  src/front/js/service/service.js
  src/front/js/service/service_worker.js
  src/front/js/service/workers.js
Labels: enhancement

#36 Service/functions/refactor
  src/front/js/pages/companyRegisterStep2/index.jsx
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/serviceList/index.jsx
  src/front/js/pages/servicesWorkers/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/service/booking.js
  src/front/js/service/company.js
  src/front/js/service/index.js
  src/front/js/service/service_worker.js
  src/front/js/service/services.js
  src/front/js/service/user.js
  src/front/js/service/workers.js
Labels: enhancement

#39 Front end update service list
  src/front/js/components/imgProfile/index.jsx
  src/front/js/components/navbar/index.jsx
  src/front/js/components/profileForm/index.jsx
  src/front/js/components/serviceCard/index.jsx
  src/front/js/components/updateMessage/index.jsx
  src/front/js/components/updateMessage/updateMessage.module.css
  src/front/js/components/updateServiceCard/index.jsx
  src/front/js/components/updateServiceCard/updateServiceCard.module.css
  src/front/js/layout.js
  src/front/js/pages/RecoveryPassword/index.jsx
  src/front/js/pages/companyDetails/index.jsx
  src/front/js/pages/createService/index.jsx
  src/front/js/pages/profile/index.jsx
  src/front/js/pages/serviceList/index.jsx
  src/front/js/pages/updatePassword/index.jsx
  src/front/js/pages/updatePassword/styles.css
  src/front/js/pages/updateService/index.jsx
  src/front/js/pages/userDashboard/index.jsx
  src/front/js/service/index.js
  src/front/js/service/service.js
  src/front/js/service/services.js
Labels: enhancement

#40 Front end service detail
  src/front/js/components/bigContainer/index.jsx
  src/front/js/components/serviceCard/index.jsx
  src/front/js/components/serviceCard/serviceCard.module.css
  src/front/js/components/serviceDetailCard/index.jsx
  src/front/js/components/serviceDetailCard/serviceDetailCard.module.css
  src/front/js/components/updateServiceCard/index.jsx
  src/front/js/components/updateServiceCard/updateServiceCard.module.css
  src/front/js/layout.js
  src/front/js/pages/serviceDetail/index.jsx
  src/front/js/pages/updateService/index.jsx
Labels: enhancement

#42 Refactor/backend
  migrations/versions/35557f22f5de_.py
  migrations/versions/5472f50d81d8_.py
  src/api/domain/booking/controller.py
  src/api/domain/booking/repository.py
  src/api/domain/booking/route.py
  src/api/domain/services/controller.py
  src/api/domain/services/repository.py
  src/api/domain/services/route.py
  src/api/domain/users/controller.py
  src/api/domain/users/repository.py
  src/api/domain/users/route.py
  src/api/domain/workers/controller.py
  src/api/domain/workers/route.py
  src/api/models/booking.py
  src/api/models/company.py
  src/api/models/services.py
  src/api/models/services_workers.py
  src/api/models/workers.py
  src/front/js/pages/companyDetails/index.jsx
Labels: enhancement

#44 Back end update worker
  src/api/domain/workers/controller.py
  src/api/domain/workers/repository.py
  src/api/domain/workers/route.py
  src/front/js/layout.js
Labels: enhancement
